compile:
	pandoc -s ./Assignment\ 1.md --template=../../../../Templates/template.tex --pdf-engine=xelatex -o ./Assignment\ 1.pdf
	#pandoc -s Assignment\ 1.md --verbose --template=../../../../Templates/mla-template.tex --csl=../../../../Templates/mla.csl --bibliography=../../../../Templates/bib/mla.bib --pdf-engine=xelatex -o Assignment\ 1.pdf
